type = "directrequest"
schemaVersion = 1
name = "(EA) Random > Uint256[]"
contractAddress = "<<<<OPERATOR CONTRACT ADDRESS>>>>"
maxTaskDuration = "0s"
observationSource = """
    decode_log   [type=ethabidecodelog
                  abi="OracleRequest(bytes32 indexed specId, address requester, bytes32 requestId, uint256 payment, address callbackAddr, bytes4 callbackFunctionId, uint256 cancelExpiration, uint256 dataVersion, bytes data)"
                  data="$(jobRun.logData)"
                  topics="$(jobRun.logTopics)"]
    decode_cbor  [type=cborparse data="$(decode_log.data)"]
    bridge_ea_random        [type=bridge name="local_random", requestData="{\\"id\\": $(jobSpec.externalJobID), \\"data\\": { \\"size\\": $(decode_cbor.size)}}"]
    parse        [type=jsonparse path="data,result" data="$(bridge_ea_random)"]
    encode_data  [type=ethabiencode abi="(bytes32 requestId, uint256[] value)" data="{ \\"requestId\\": $(decode_log.requestId), \\"value\\": $(parse) }"]
    encode_tx    [type=ethabiencode
                  abi="fulfillOracleRequest2(bytes32 requestId, uint256 payment, address callbackAddress, bytes4 callbackFunctionId, uint256 expiration, bytes calldata data)"
                  data="{\\"requestId\\": $(decode_log.requestId), \\"payment\\": $(decode_log.payment), \\"callbackAddress\\": $(decode_log.callbackAddr), \\"callbackFunctionId\\": $(decode_log.callbackFunctionId), \\"expiration\\": $(decode_log.cancelExpiration), \\"data\\": $(encode_data)}"
                 ]
    submit_tx    [type=ethtx to="<<<<OPERATOR CONTRACT ADDRESS>>>>" data="$(encode_tx)"]

    decode_log ->  decode_cbor -> bridge_ea_random -> parse -> encode_data -> encode_tx -> submit_tx
"""
externalJobID = "8f8d40f5-c8c9-46b3-8b72-7b76bfb7ee56"