dotenv: .env

dependencies:
  - smartcontractkit/chainlink@1.0.0

compiler: 
  solc:
    remappings:
      - '@chainlink=smartcontractkit/chainlink@1.0.0'

wallets: 
  from_key: ${PRIVATE_KEY}

networks:
  kovan: 
    link_token: '0xa36085f69e2889c224210f603d836748e7dc0088'
    local: False
    mock: False
    verify: True
    oracle: '0xc57B33452b4F7BB189bB5AfaE9cc4aBa1f7a4FD8'
    jobId: 'd5270d1c311941d0b08bead21fea7747'
    fee: 100000000000000000