dotenv: .env

wallets: 
  from_key: ${PRIVATE_KEY}
   
dependencies: 
  - smartcontractkit/chainlink-brownie-contracts@1.1.1

compiler: 
  solc:
      remappings: 
        - '@chainlink=smartcontractkit/chainlink-brownie-contracts@1.1.1'

networks:
  default: development
  rinkeby:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    verify: True
  mainnet-fork:
    eth_usd_price_feed: '0x8A753747A1Fa494EC906cE90E9f37563A8AF630e'
    local: True
  ganache-local: 
    local: True
    deploy_mocks: True
  development:
    local: True
    deploy_mocks: True